apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 9090            # Changed to 9090
    protocol: TCP
    targetPort: 8080       # Your application is still listening on port 8080 inside the pod

