apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort     # This exposes the service on a port on each Node
  selector:
    app: myapp
  ports:
  - port: 9090
    targetPort: 8080
    nodePort: 30080   # Optional: Pick a port between 30000–32767, or let K8s choose

